schema: ./packages/server/graphql/schema/**.graphql
documents: ""
extensions:
  codegen:
    generates:
      "":
        plugins:
          - typescript
          - typescript-resolvers
      ./generated-frontend.ts:
        plugins:
          - typescript
          - typescript-resolvers
          - typescript-react-apollo
  diff:
    baseSchema: your-base-schema-here
